### PR TITLE
Fix QuantumLeap, CrateDB and MongoDB names

### PR DESCRIPTION
**Pull request by taliaga**
Warm-up PR, also to check if this is the right way to contribute to the tutorial.

I was thinking of updating it a bit in a new PR, considering the Query API has been available for a while now. Wdyt @jason-fox?

Signed-off-by: Tomas Aliaga <tomas.aliaga@martel-innovate.com>

### CODE REVIEW

**Comment by jason-fox** [comment]
Yes, a PR like this is the right idea, however I would be wary of doing a simple grep for this as the yaml files, online published on-line postman collection and URLs are a sensitive for the commands. Sometimes the dash really *is* required.

I have done a  case-sensitive change for the brand names in the text only in 78dc4a1e

QuantumLeap and CrateDB should now be consistent. MongoDB will need to be checked across the other tutorials as well.

**Comment by jason-fox** [comment]
Closing as partial fix has been manually implemented.

**Comment by taliaga** [comment]
Oh, I didn't think it'd be a problem to update the names in the docker-compose or postman collections really, because that's how I use them usually. I'm curious to know when the dash is required now hehe.

OK, thanks Jason. New PR coming up soon.

**Comment by taliaga** [comment]
In other words, what's the problem with updating also the postman collection? I'll need to that anyhow to add new query methods to QL API.

**Comment by jason-fox** [comment]
@taliaga  - There isn't  really a big issue,  purely lack of time. Changing brand-name texts within the **documentation** parts of the README can be checked by eye very quickly - altering the Postman collection, changing any cUrl commands or amending the `docker-compose.yml` would require the following:

1) Checking that the cUrl commands in the tutorial still work when copy-pasted.
2) Checking that the cUrl commands in the Japanese tutorial still work when copy-pasted.
3) Update the commands in the Postman collection JSON and check they commands still work
4) Republish the Postman collection online hosted on `documenter.getpostman.com`
5) Update and amend the  run-in-postman button.

This needs to be done each time the cUrl commands or equivalent are altered. It would be more time-efficient to accept your big updated tutorial changes for QL all together and test once rather than several times over.

Where possible PRs should be split -  documentation only  or code-based. The latter take a lot longer to verify.

**Comment by taliaga** [comment]
Got it, thanks for your explanation! Btw, nice work you've done with those tutorials.

**Pull request closed without merging**
